### ISSUE TITLE
How does this work with Iterator Helpers?

### ISSUE THREAD

**Issue by Jack-Works** [tc39/proposal-deiter#1]

**Comment by hax** [comment]
As I understand, iterator helpers those not return generators will not be affected. Those return generators pass argument of `next` (except the first arg, which I suppose should be updated as `function.sent` proposal, aka. change "1. Let _lastValue_ be `undefined`" to "1. Let _lastValue_ be `function.sent`"), 

so `const [..., last] = [1,2,3].values().map(x=>x*2)` just work (`last` will be `6`). Actually this also show the benefit of deiter solution which only do the calculation u really need.

But maybe `take(n)`, `drop(n)` should be updated to not pass arg for `n`th steps, and add `takeBack`, `dropBack` which pass `"back"` for `n`th steps.

**Comment by ljharb** [comment]
How would various API methods know they're supposed to behave differently because a `...` was used? They're just normal functions.

**Comment by hax** [comment]
@ljharb The methods don't need to know they are used by `...`. The only thing they need to do is handle `next()` in a proper way. But I may misunderstand your question if this is not what u ask.

**Comment by ljharb** [comment]
OK, how would they know to handle it differently? `next` is a normal function too, that only has `this` and its optional argument to pivot on.

**Comment by hax** [comment]
@ljharb I still don't figure out your question. Maybe we can use some helpers as example.

For instance, `Iterator.p.map` could be think roughly as:

```js
function *map(mapper) {
	for (;;) {
		const {done, value} = this.next(function.sent)
		if (done) return
		yield mapper(value)
	}
}
```

So `let [a, ..., b] = [1,2,3].values().map(x=>x*2)` just work (`a` will be `2`, `b` will be `6`).

**Comment by conartist6** [comment]
I don't think that code works, does it?

Your problem is that generators don't have the ability to receive any variable passed to them as `next(value)` until after they've generated the first value of output, so even though the syntax looks fine (`iterable[Symbol.iterator]().next('back')`), in a real generator function you have to write something like `isBack = yield value`, which I think make the problem clear: you must yield the value before you know whether it's a forwards or a backwards iteration.

**Comment by conartist6** [comment]
Ah sorry I'm playing catch-up. Remedying that situation is the purpose of the [function.sent proposal](https://github.com/tc39/proposal-function.sent) (for any other latecomers).

**Comment by hax** [comment]
Copy from other comment:

Some iterator helpers already limit the reversibility. eg. `take(n)`, actually it means take the first n elements, so it already one-direction and no way to reverse.

Or in double-ended proposal, iterators always reversible (means u could always `reverse` it), because it just change the end which could be iterated.

There are three type of iterables as double-ended iteration:

1. double-ended, which could be understand as it support both `take(n)` and `takeLast(n)`
2. front-only, which could be understand as it only support `take(n)`, reverse it will transform it to back-only
3. back-only, which could be understand as it only support `takeLast(n)`, reverse it will transform it to front-only

Here are the simple result table for iterator helpers (note, most aggregator methods like `toArray`, `every`, etc. are direction-neutral so not listed here) :

method  \  upstream | double-ended | front-only | back-only
-|-|-|-
`forEach` | ✅ double-ended | ✅ front-only | ✅ back-only
`map` | ✅ double-ended | ✅ front-only | ✅ back-only
`filter` | ✅ double-ended | ✅ front-only | ✅ back-only
`flatMap` | ✅ double-ended | ✅ front-only | ✅ back-only
`reverse` | ✅ double-ended | ✅ back-only | ✅ front-only
`asIndexedPairs` |  ✅ front-only | ✅ front-only | ❌
`take` | ✅ front-only | ✅ front-only | ❌
`drop` | ✅ double-ended | ✅ front-only | ❌
`find` | ✅ | ✅ | ❌
`reduce` | ✅ | ✅  | ❌
`asLastIndexedPairs` | ✅ back-only | ❌ | ✅ back-only
`takeLast` | ✅ back-only | ❌ | ✅ back-only
`dropLast` | ✅ double-ended | ❌ | ✅ back-only
`findLast` | ✅ | ❌ | ✅
`reduceRight` | ✅ | ❌ | ✅

Note: How to read the table: `upstream.method() => tablecell`, for example, `doubleEnded.map() => doubleEnded`, `frontOnly.reverse() => backOnly`, `frontOnly.takeLast() => ❌` (❌  means throw TypeError)

About `flatMap`: If the inner iterator of `flatMap` have the incompatible type, trigger TypeError.

**Comment by conartist6** [comment]
Actually you'd need to amend that map implementation to this one I think:

```js
function *map(source, mapper) {
  const iterator = source[Symbol.iterator]();
  let done = false, value;
  try {
    for (;;) {
      ({done, value} = iterator.next(function.sent));
      if (done) return;
      yield mapper(value);
    }
  } finally {
    if (!done) iterator.return();
  }
}
```

**Comment by conartist6** [comment]
Your only truly backward compatible way of marking things is going to be with a different protocol, e.g. something like `Symbol.deiterator`

**Comment by hax** [comment]
> Actually you'd need to amend that map implementation to this one I think:

Yeah, the built-in `Iterator.prototype.map` or any production-level iter-tools lib should deal with many spec details, and I suppose it's not trivial to implement it via generator functions, because generator functions lack some fine controls and always need boilerplate code like `try/catch/finally` wrapper. So my previous code example only roughly present the core part and omit those boilerplate code.

> 
> ```js
> function *map(source, mapper) {
>   const iterator = source[Symbol.iterator]();
>   let done = false, value;
>   try {
>     for (;;) {
>       ({done, value} = iterator.next(function.sent));
>       if (done) return;
>       yield mapper(value);
>     }
>   } finally {
>     if (!done) iterator.return();
>   }
> }
> ```

Personally I would love to call `source[Symbol.iterator]()` to get the iterator object, but current iterator helpers proposal choose to use `source` directly (aka. `source` must be an iterator object, not a general iterable), at least that's the status what I checked last time. This is controversial (I love to call because it could keep the non-one-shot nature of the upstream iterable), but it seems some champions of the proposal insist on that. You'd better discuss that in the repo of iterator helpers, if u care about that.

And yeah, we should use `finally` to close the source iterator, but don't forget iterator may not have `return` method, so it should be `iterator.return?.()`. And we may also need `catch(e) { iterator.throw?.(e) }` to propagate errors to the source (iterator helpers proposal do not need do that because it's the iterator itself).

Anyway these are the details which belongs to iterator helpers proposal or the iter-tools lib.

**Comment by hax** [comment]
> Your only truly backward compatible way of marking things is going to be with a different protocol, e.g. something like Symbol.deiterator

Of coz introducing `Symbol.deIterator` would be a way. But we have a [separate issue](https://github.com/tc39/proposal-deiter/issues/5) for exploring other possibilities and compare them.

**Comment by conartist6** [comment]
I wrote mine as `source[Symbol.iterator]()` because that's what the code will look like when written in a library, where `source` is untrusted. I don't think there's any problem with using `this` in iterator helper methods where it's clear that `this` is an iterator.

I also don't propagate throws in `iter-tools`. It's not clear to me what it means to throw into an iterator outside the context of writing a coroutine.

**Comment by hax** [comment]
As iterator helpers now don't pass the protocol, we have to switch to `nextLast()` API, and upgrade the iterator helpers in this proposals or future proposals.
